server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/my-app-realm

keycloak:
  auth-server-url: http://localhost:8080/
  realm: my-app-realm
  resource: product-service
  credentials:
    secret: YOUR_SECRET
  grant-type: urn:ietf:params:oauth:grant-type:uma-ticket
  bearer-only: true